export const ON_FORM_NAME_CHANGE_ACTION = "ON FORM NAME CHANGE ACTION";
export const ON_FORM_DESCRIPTION_CHANGE_ACTION = "ON FORM DESCRIPTION CHANGE ACTION";
export const ADD_DATA_IN_LIST = "ADD DATA IN LIST";
export const RESET_ALL_DATA = "RESET ALL DATA";
export const DELETE_ITEM_FROM_LIST = "DELETE ITEM FROM LIST";